# Generated by Django 5.0.7 on 2024-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
    ]
